[package]
name = "arachnea-scrapyfy"
version = "0.1.0"
edition = "2021"

[features]
test-support = []
default = ["ghostwire"]
ghostwire = ["arachnea-http/ghostwire"]
tauri-cloudflare-solver = ["arachnea-http/ghostwire", "arachnea-http/tauri-cloudflare-solver"]
chaser-cf = ["arachnea-http/ghostwire", "arachnea-http/chaser-cf"]

[dependencies]
quick_html2md = "0.2.1"
anyhow.workspace = true
arachnea-core = { path = "../arachnea-core" }
arachnea-http = { path = "../arachnea-http", default-features = false }
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
http.workspace = true
mathexpr.workspace = true
regex.workspace = true
scopeguard.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
url.workspace = true
urlencoding.workspace = true
tracing.workspace = true
