[package]
name = "arachnea-scrapyfy"
version = "0.1.0"
edition = "2021"

[features]
test-support = []
default = ["ghostwire"]
ghostwire = ["arachnea-http/ghostwire"]
tauri-cloudflare-solver = ["arachnea-http/ghostwire", "arachnea-http/tauri-cloudflare-solver"]
chaser-cf = ["arachnea-http/ghostwire", "arachnea-http/chaser-cf"]
arachnea-proxy = ["arachnea-http/arachnea-proxy", "dep:arachnea-proxy"]

[dependencies]
quick_html2md.workspace = true
anyhow.workspace = true
aes.workspace = true
arachnea-core = { path = "../arachnea-core" }
arachnea-http = { path = "../arachnea-http", default-features = false }
arachnea-proxy = { path = "../arachnea-proxy", default-features = false, features = ["core", "persistence"], optional = true }
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
http.workspace = true
evalexpr.workspace = true
regex.workspace = true
base64.workspace = true
boa_engine.workspace = true
cbc.workspace = true
scopeguard.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
url.workspace = true
urlencoding.workspace = true
tracing.workspace = true
